[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { path = "../models" }
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
dotenvy.workspace = true
